In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)

# Data Loading And Initial Overview

In [10]:
df = pd.read_csv(r"C:\Users\adhar\Downloads\Sample - Superstore.csv", encoding="latin1")
df.head()
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,03/03/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,03/03/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,03/03/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,05/04/2017,05/09/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [3]:
# Basic overview
print("Shape (rows, cols):", df.shape)

print("\nColumn data types:")
print(df.dtypes)

print("\nSummary statistics (numeric + categorical):")
print(df.describe(include='all').T)

print("\nMissing values per column:")
print(df.isna().sum())

print("\nNumber of duplicate rows:", df.duplicated().sum())

Shape (rows, cols): (9994, 21)

Column data types:
Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

Summary statistics (numeric + categorical):
                count unique              top  freq          mean  \
Row ID         9994.0    NaN              NaN   NaN        4997.5
Order ID         9994   5009   CA-2017-100111    14           NaN
Order Date       9994   1237       09/05/2016    38           NaN
Ship Date        9994   1334       12/16/2015    35           NaN
Ship Mode        9994      4   Standard Class  5968           NaN
Customer ID      9994    793         WB-21850    37           NaN
Customer Name    9994    793    William Brown    37           NaN
Segment          9994      3         Consumer  5191           NaN
Country          9994      1    United States  9994           NaN
City             9994    531    New York City   915           NaN
State            9994     49       California  2001           NaN
Postal Code    9994.0    NaN              NaN   NaN  55190.379428
Region           9994      4             West  3203           NaN
Product ID       9994   1862  OFF-PA-10001970    19           NaN
Category         9994      3  Office Supplies  6026           NaN
Sub-Category     9994     17          Binders  1523           NaN
Product Name     9994   1850  Staple envelope    48           NaN
Sales          9994.0    NaN              NaN   NaN    229.858001
Quantity       9994.0    NaN              NaN   NaN      3.789574
Discount       9994.0    NaN              NaN   NaN      0.156203
Profit         9994.0    NaN              NaN   NaN     28.656896

                       std       min      25%      50%      75%       max
Row ID         2885.163629       1.0  2499.25   4997.5  7495.75    9994.0
Order ID               NaN       NaN      NaN      NaN      NaN       NaN
Order Date             NaN       NaN      NaN      NaN      NaN       NaN
Ship Date              NaN       NaN      NaN      NaN      NaN       NaN
Ship Mode              NaN       NaN      NaN      NaN      NaN       NaN
Customer ID            NaN       NaN      NaN      NaN      NaN       NaN
Customer Name          NaN       NaN      NaN      NaN      NaN       NaN
Segment                NaN       NaN      NaN      NaN      NaN       NaN
Country                NaN       NaN      NaN      NaN      NaN       NaN
City                   NaN       NaN      NaN      NaN      NaN       NaN
State                  NaN       NaN      NaN      NaN      NaN       NaN
Postal Code    32063.69335    1040.0  23223.0  56430.5  90008.0   99301.0
Region                 NaN       NaN      NaN      NaN      NaN       NaN
Product ID             NaN       NaN      NaN      NaN      NaN       NaN
Category               NaN       NaN      NaN      NaN      NaN       NaN
Sub-Category           NaN       NaN      NaN      NaN      NaN       NaN
Product Name           NaN       NaN      NaN      NaN      NaN       NaN
Sales           623.245101     0.444    17.28    54.49   209.94  22638.48
Quantity           2.22511       1.0      2.0      3.0      5.0      14.0
Discount          0.206452       0.0      0.0      0.2      0.2       0.8
Profit          234.260108 -6599.978  1.72875   8.6665   29.364  8399.976

Missing values per column:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Number of duplicate rows: 0

In [4]:
# Make column names neat
df.columns = df.columns.str.strip()

# Trim spaces inside text columns 
str_cols = df.select_dtypes(include="object").columns
df[str_cols] = df[str_cols].apply(lambda s: s.str.strip())

# Removing Duplicates

In [5]:
# Remove duplicate rows
before = len(df)
df = df.drop_duplicates()
print(f"Removed {before - len(df)} duplicate rows")

Removed 0 duplicate rows

# Correcting Datatypes

In [6]:
# Fix dates and numbers
# Dates
for c in ['Order Date', 'Ship Date']:
    if c in df.columns:
        df[c] = pd.to_datetime(df[c], errors='coerce')

# Numbers
for c in ['Sales','Quantity','Discount','Profit','Shipping Cost']:
    if c in df.columns:
        df[c] = pd.to_numeric(df[c], errors='coerce')

In [11]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,03/03/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,03/03/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,03/03/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,05/04/2017,05/09/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

# Handling Missing Values

In [7]:
print("\nMissing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [8]:
print("Missing values (top 10 columns):")
print(df.isna().sum().sort_values(ascending=False).head(10))
df.info()

Missing values (top 10 columns):
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

# Creating Derived Columns

In [15]:
# Derived Column 1 - Profit Margin (Profit / Sales)
df['Profit_Margin'] = (df['Profit'] / df['Sales']).round(2)

In [16]:
#  Derived Column 2 - Sales per Quantity (unit price estimate)
df['Sales_per_Quantity'] = (df['Sales'] / df['Quantity']).round(2)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Row ID              9994 non-null   int64
 1   Order ID            9994 non-null   object
 2   Order Date          9994 non-null   object
 3   Ship Date           9994 non-null   object
 4   Ship Mode           9994 non-null   object
 5   Customer ID         9994 non-null   object
 6   Customer Name       9994 non-null   object
 7   Segment             9994 non-null   object
 8   Country             9994 non-null   object
 9   City                9994 non-null   object
 10  State               9994 non-null   object
 11  Postal Code         9994 non-null   int64
 12  Region              9994 non-null   object
 13  Product ID          9994 non-null   object
 14  Category            9994 non-null   object
 15  Sub-Category        9994 non-null   object
 16  Product Name        9994 non-null   object
 17  Sales               9994 non-null   float64
 18  Quantity            9994 non-null   int64
 19  Discount            9994 non-null   float64
 20  Profit              9994 non-null   float64
 21  Profit_Margin       9994 non-null   float64
 22  Sales_per_Quantity  9994 non-null   float64
dtypes: float64(5), int64(3), object(15)
memory usage: 1.8+ MB

# Filtering Data

In [18]:
#  1: Filter high value orders (Sales > 1000)
high_value_orders = df[df['Sales'] > 1000]

In [19]:
high_value_orders.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Profit_Margin,Sales_per_Quantity
10,11,CA-2014-115812,06/09/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184,9,0.2,85.3092,0.05,189.58
24,25,CA-2015-106320,9/25/2015,9/30/2015,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,Utah,84057,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.630,3,0.0,240.2649,0.23,348.21
27,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430,7,0.5,-1665.0522,-0.54,440.49
35,36,CA-2016-117590,12/08/2016,12/10/2016,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544,7,0.2,123.4737,0.11,156.79
54,55,CA-2016-105816,12/11/2016,12/17/2016,Standard Class,JM-15265,Janet Molinari,Corporate,United States,New York City,New York,10024,East,TEC-PH-10002447,Technology,Phones,AT&T CL83451 4-Handset Telephone,1029.950,5,0.0,298.6855,0.29,205.99
67,68,CA-2014-106376,12/05/2014,12/10/2014,Standard Class,BS-11590,Brendan Sweed,Corporate,United States,Gilbert,Arizona,85234,West,OFF-AR-10002671,Office Supplies,Art,Hunt BOSTON Model 1606 High-Volume Electric Pe...,1113.024,8,0.2,111.3024,0.10,139.13
149,150,CA-2016-114489,12/05/2016,12/09/2016,Standard Class,JE-16165,Justin Ellison,Corporate,United States,Franklin,Wisconsin,53132,Central,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",1951.840,8,0.0,585.5520,0.30,243.98
165,166,CA-2014-139892,09/08/2014,09/12/2014,Standard Class,BM-11140,Becky Martin,Consumer,United States,San Antonio,Texas,78207,Central,TEC-MA-10000822,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,8159.952,8,0.4,-1359.9920,-0.17,1019.99
167,168,CA-2014-139892,09/08/2014,09/12/2014,Standard Class,BM-11140,Becky Martin,Consumer,United States,San Antonio,Texas,78207,Central,FUR-CH-10004287,Furniture,Chairs,SAFCO Arco Folding Chair,1740.060,9,0.3,-24.8580,-0.01,193.34
215,216,CA-2015-146262,01/02/2015,01/09/2015,Standard Class,VW-21775,Victoria Wilson,Corporate,United States,Medina,Ohio,44256,East,TEC-MA-10000864,Technology,Machines,Cisco 9971 IP Video Phone Charcoal,1188.000,9,0.7,-950.4000,-0.80,132.00

In [20]:
# 2: Aggregate total sales by Region
region_sales = df.groupby('Region')['Sales'].sum().reset_index()

In [21]:
region_sales.head(10)

    Region        Sales
0  Central  501239.8908
1     East  678781.2400
2    South  391721.9050
3     West  725457.8245

In [22]:
# Final dataset shape 
print(f"\nData shape after cleaning: {df.shape}")

Data shape after cleaning: (9994, 23)